"""
Django settings for smart_leave_sys project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# HARDCODED: This is a development secret key. In production, use environment variables (e.g., os.environ.get('SECRET_KEY'))
SECRET_KEY = 'django-insecure-1ns_b-jrq_)ysa^5&*rll78+5n7q8#*sag1-u9@pt0%lmfb6cy'

# SECURITY WARNING: don't run with debug turned on in production!
# HARDCODED: Debug mode is enabled for development. Set to False in production
DEBUG = True

# HARDCODED: Empty list allows all hosts in DEBUG mode. In production, specify allowed domains (e.g., ['yourdomain.com'])
ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'smart_leave_sys.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'smart_leave_sys.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'smart_leave_db',  # HARDCODED: Database name for the leave management system
        'USER': 'postgres',  # HARDCODED: Default PostgreSQL username. Use environment variables in production
        'PASSWORD': 'postgres',  # HARDCODED: Default PostgreSQL password. NEVER commit real passwords! Use environment variables
        'HOST': '127.0.0.1',  # HARDCODED: Localhost for development. Change to actual DB host in production
        'PORT': '5432',  # HARDCODED: Default PostgreSQL port
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'  # HARDCODED: English (US) as default language

TIME_ZONE = 'UTC'  # HARDCODED: UTC timezone. Consider changing to local timezone (e.g., 'Asia/Colombo') if needed

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'  # HARDCODED: URL prefix for static files

MEDIA_URL = '/media/'  # HARDCODED: URL prefix for user-uploaded media files
MEDIA_ROOT = BASE_DIR / 'media'  # HARDCODED: Directory path for storing uploaded files

AUTH_USER_MODEL = 'core.User'

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'  # HARDCODED: Console backend for development. Use SMTP backend in production
